#
# This file will be read by node-config
# See https://github.com/node-config/node-config/wiki/Environment-Variables#custom-environment-variables
#

webserver:
  hostname: "RETRO3_WEBSERVER_HOSTNAME"
  port:
    __name: "RETRO3_WEBSERVER_PORT"
    __format: "json"
  https:
    __name: "RETRO3_WEBSERVER_HTTPS"
    __format: "json"

federation:
  sign_federated_fetches:
    __name: "RETRO3_SIGN_FEDERATED_FETCHES"
    __format: "json"

secrets:
  retro3: "RETRO3_SECRET"

trust_proxy:
  __name: "RETRO3_TRUST_PROXY"
  __format: "json"

database:
  hostname: "RETRO3_DB_HOSTNAME"
  port:
    __name: "RETRO3_DB_PORT"
    __format: "json"
  name: "RETRO3_DB_NAME"
  suffix: "RETRO3_DB_SUFFIX"
  username: "RETRO3_DB_USERNAME"
  password: "RETRO3_DB_PASSWORD"
  ssl:
    __name: "RETRO3_DB_SSL"
    __format: "json"

redis:
  hostname: "RETRO3_REDIS_HOSTNAME"
  port:
    __name: "RETRO3_REDIS_PORT"
    __format: "json"
  auth: "RETRO3_REDIS_AUTH"

smtp:
  hostname: "RETRO3_SMTP_HOSTNAME"
  port:
    __name: "RETRO3_SMTP_PORT"
    __format: "json"
  username: "RETRO3_SMTP_USERNAME"
  password: "RETRO3_SMTP_PASSWORD"
  tls:
    __name: "RETRO3_SMTP_TLS"
    __format: "json"
  disable_starttls:
    __name: "RETRO3_SMTP_DISABLE_STARTTLS"
    __format: "json"
  from_address: "RETRO3_SMTP_FROM"

object_storage:
  enabled:
    __name: "RETRO3_OBJECT_STORAGE_ENABLED"
    __format: "json"

  endpoint: "RETRO3_OBJECT_STORAGE_ENDPOINT"

  region: "RETRO3_OBJECT_STORAGE_REGION"

  upload_acl:
    public: "RETRO3_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC"
    private: "RETRO3_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE"

  proxy:
    proxify_private_files:
      __name: "RETRO3_OBJECT_STORAGE_PROXY_PROXIFY_PRIVATE_FILES"
      __format: "json"

  credentials:
    access_key_id: "RETRO3_OBJECT_STORAGE_CREDENTIALS_ACCESS_KEY_ID"
    secret_access_key: 'RETRO3_OBJECT_STORAGE_CREDENTIALS_SECRET_ACCESS_KEY'

  max_upload_part:
    __name: "RETRO3_OBJECT_STORAGE_MAX_UPLOAD_PART"
    __format: "json"

  streaming_playlists:
    bucket_name: "RETRO3_OBJECT_STORAGE_STREAMING_PLAYLISTS_BUCKET_NAME"
    prefix: "RETRO3_OBJECT_STORAGE_STREAMING_PLAYLISTS_PREFIX"
    base_url: "RETRO3_OBJECT_STORAGE_STREAMING_PLAYLISTS_BASE_URL"
    upload_acl: "RETRO3_OBJECT_STORAGE_UPLOAD_ACL"

  web_videos:
    bucket_name: "RETRO3_OBJECT_STORAGE_WEB_VIDEOS_BUCKET_NAME"
    prefix: "RETRO3_OBJECT_STORAGE_WEB_VIDEOS_PREFIX"
    base_url: "RETRO3_OBJECT_STORAGE_WEB_VIDEOS_BASE_URL"

webadmin:
  configuration:
    edition:
      allowed:
        __name: "RETRO3_WEBADMIN_CONFIGURATION_EDITION_ALLOWED"
        __format: "json"

log:
  level: "RETRO3_LOG_LEVEL"
  log_ping_requests:
    __name: "RETRO3_LOG_PING_REQUESTS"
    __format: "json"

user:
  video_quota:
    __name: "RETRO3_USER_VIDEO_QUOTA"
    __format: "json"

admin:
  email: "RETRO3_ADMIN_EMAIL"

contact_form:
  enabled:
    __name: "RETRO3_CONTACT_FORM_ENABLED"
    __format: "json"

signup:
  enabled:
    __name: "RETRO3_SIGNUP_ENABLED"
    __format: "json"
  limit:
    __name: "RETRO3_SIGNUP_LIMIT"
    __format: "json"

search:
  remote_uri:
    users:
      __name: "RETRO3_SEARCH_REMOTEURI_USERS"
      __format: "json"
    anonymous:
      __name: "RETRO3_SEARCH_REMOTEURI_ANONYMOUS"
      __format: "json"

import:
  videos:
    http:
      enabled:
        __name: "RETRO3_IMPORT_VIDEOS_HTTP"
        __format: "json"
    torrent:
      enabled:
        __name: "RETRO3_IMPORT_VIDEOS_TORRENT"
        __format: "json"

transcoding:
  enabled:
    __name: "RETRO3_TRANSCODING_ENABLED"
    __format: "json"
  threads:
    __name: "RETRO3_TRANSCODING_THREADS"
    __format: "json"
  resolutions:
    144p:
      __name: "RETRO3_TRANSCODING_144P"
      __format: "json"
    240p:
      __name: "RETRO3_TRANSCODING_240P"
      __format: "json"
    360p:
      __name: "RETRO3_TRANSCODING_360P"
      __format: "json"
    480p:
      __name: "RETRO3_TRANSCODING_480P"
      __format: "json"
    720p:
      __name: "RETRO3_TRANSCODING_720P"
      __format: "json"
    1080p:
      __name: "RETRO3_TRANSCODING_1080P"
      __format: "json"
    1440p:
      __name: "RETRO3_TRANSCODING_1440P"
      __format: "json"
    2160p:
      __name: "RETRO3_TRANSCODING_2160P"
      __format: "json"
  web_videos:
    enabled:
      __name: "RETRO3_TRANSCODING_WEB_VIDEOS_ENABLED"
      __format: "json"
  hls:
    enabled:
      __name: "RETRO3_TRANSCODING_HLS_ENABLED"
      __format: "json"

instance:
  name: "RETRO3_INSTANCE_NAME"
  description: "RETRO3_INSTANCE_DESCRIPTION"
  terms: "RETRO3_INSTANCE_TERMS"
