name: 🚀 Installation/Upgrade Issue
description: Use this template for build/installation/upgrade issues
body:
  - type: markdown
    attributes:
      value: |
        Please check the official documentation first:
          - Classic installation: https://docs.joinretro3.org/install/any-os
          - Docker installation: https://docs.joinretro3.org/install/docker

  - type: markdown
    attributes:
      value: |
        Please search among past open/closed issues for a similar one beforehand:
          - https://github.com/juztamau5/retro3/issues?q=
          - https://framacolibri.org/c/retro3

  - type: textarea
    attributes:
      label: Describe the problem

  - type: textarea
    attributes:
      label: Additional information
      value: |
          * retro3 instance URL:
          * retro3 version:
          * NodeJS version:
          * Ffmpeg version:
          * Redis version:
          * PostgreSQL version:
